name: 'Run tests'
description: 'Creates SDK and Uploads artifacts'
inputs:
  shell:
    require: false
    type: string
  package-name:
    required: true
    type: string
  package-sdk:
    default: false
    required: false
    type: boolean
  os:
    required: true
    type: string
  arch:
    required: true
    type: string
  git-tag:
    required: true
    type: string
  aws-access-key-id:
    required: true
    type: string
  aws-secret-access-key:
    required: true
    type: string
  aws-region:
    required: true
    type: string

runs:
  using: "composite"
  permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout
  steps:
    - name: Download SDK
      if: ${{ inputs.package-sdk == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{inputs.package-name}}-sdk-${{inputs.os}}-${{inputs.arch}}
        path: |
          artifacts/${{inputs.package-name}}-sdk
    - name: Download ${{inputs.package-name}}
      uses: actions/download-artifact@v4
      with:
        name: ${{inputs.package-name}}-${{inputs.os}}-${{inputs.arch}}
        path: |
          artifacts/${{inputs.package-name}}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::353328028284:role/github-actions-runner
        role-session-name: github-actions-runner-session
        aws-region: ${{ inputs.aws-region }}
    - name: Publish to S3
      shell: ${{inputs.shell}}
      env:
        BUCKET_NAME: febio-packages
        OS: ${{inputs.os}}
        REF_NAME: ${{ github.ref_name}}
        PACKAGE_NAME: ${{inputs.package-name}}
        GIT_TAG: ${{ inputs.git-tag }}
      run: |
        ci/${{inputs.os}}/publish-to-s3.sh
