name: 'Run tests'
description: 'Creates SDK and Uploads artifacts'
inputs:
  shell:
    required: false
    default: bash
    type: string
  package-name:
    required: true
    type: string
  os:
    required: true
    type: string
  arch:
    required: true
    type: string
  script:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{inputs.package-name}}-${{inputs.os}}-${{inputs.arch}}
        path: |
          cmbuild
    - name: Run test suite
      shell: ${{inputs.shell}}
      run: |
        ${{ inputs.script }}
    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: testsuite-${{inputs.os}}-${{inputs.arch}}-logs
        path: |
          TestSuite/Verify4/*.log
          TestSuite/Logs*.txt
