on:
  workflow_call:
    inputs:
      shell:
        required: false
        default: bash
        type: string
      package-name:
        required: true
        type: string
      package-sdk:
        default: false
        required: false
        type: boolean
      requires-sdk:
        default: false
        required: false
        type: boolean
      sdk-config:
        required: false
        type: string
      os:
        default: macOS
        required: false
        type: string
      arch:
        default: X64
        required: false
        type: string
      runTests:
        description: "Run tests?"
        required: false
        type: boolean
        default: false
      aws-region:
        default: us-east-1
        required: false
        type: string
      aws-role-to-assume:
        required: false
        default: arn:aws:iam::353328028284:role/github-actions-runner
        type: string
      aws-role-session-name:
        required: false
        default: febio-github-actions-runner-session
        type: string
      aws-availability-zone:
        required: false
        default: us-east-1b
        type: string

jobs:
  build:
    name: Clone and build
    runs-on: self-hosted
    outputs:
      git_describe: ${{ steps.git-describe.outputs.git_describe }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          submodules: 'true'
      - id: git-describe
        name: Git Describe
        uses: febiosoftware/febio-workflows/.github/actions/git-describe@develop
        with:
          shell: ${{ inputs.shell }}
      - name: Build
        uses: febiosoftware/febio-workflows/.github/actions/build@develop
        with:
          shell: ${{ inputs.shell }}
          package-name: ${{ inputs.package-name }}
          requires-sdk: ${{ inputs.requires-sdk }}
          sdk-config: ${{ inputs.sdk-config }}
          package-sdk: ${{ inputs.package-sdk }}
          script: ci/${{inputs.os}}/build.sh
          os: ${{inputs.os}}
          arch: ${{inputs.arch}}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}
  tests:
    if: inputs.runTests
    name: Run test suite
    needs:
      - build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: 'true'
      - name: Tests
        uses: tundranerd/febio-workflows/.github/actions/run-tests@oidc-wip-aws
        with:
          script: ci/${{inputs.os}}/test.sh
          shell: ${{ inputs.shell }}
          package-name: ${{ inputs.package-name }}
          os: ${{inputs.os}}
          arch: ${{inputs.arch}}
